import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { commonStyles, useTheme } from '../theme';

export default function HomeScreen() {
  const colors = useTheme();
  return (
    <View style={commonStyles.screen}>
      <Text style={[commonStyles.title, { color: colors.primary }]}>Home</Text>
      <Text style={[commonStyles.caption, styles.meta]}>
        This Home screen was generated by ApkBuilder.
      </Text>
      <View style={[styles.card, { borderColor: colors.border }]}>
        <Text style={{ color: colors.text }}>Customize this screen in the source editor.</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  meta: {
    marginTop: 4,
    marginBottom: 16,
  },
  card: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
    backgroundColor: '#FFFFFF',
  },
});
